export interface SeedLegalDoc {
  docCode: string;
  title: string;
  docType: "Luật" | "Bộ luật" | "Nghị định" | "Thông tư" | "Quyết định" | "Nghị quyết";
  issuingAuthority: string;
  issuedDate: string;
  effectiveDate: string;
  status: "ACTIVE" | "EXPIRED" | "REPLACED";
  fullCitation: string;
  categoryId: string;
}

export const CURATED_LEGAL_DOCUMENTS: SeedLegalDoc[] = [
  // --- 1. HÀNH CHÍNH, VĂN THƯ, LƯU TRỮ, TỔ CHỨC BỘ MÁY ---
  {
    docCode: "30/2020/NĐ-CP",
    title: "Nghị định về công tác văn thư",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-03-05",
    effectiveDate: "2020-03-05",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 30/2020/NĐ-CP ngày 05 tháng 3 năm 2020 của Chính phủ về công tác văn thư;",
    categoryId: "administrative",
  },
  {
    docCode: "80/2015/QH13",
    title: "Luật Ban hành văn bản quy phạm pháp luật",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-06-22",
    effectiveDate: "2016-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Ban hành văn bản quy phạm pháp luật ngày 22 tháng 6 năm 2015;",
    categoryId: "administrative",
  },
  {
    docCode: "63/2020/QH14",
    title: "Luật sửa đổi, bổ sung một số điều của Luật Ban hành văn bản quy phạm pháp luật",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2020-06-18",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật sửa đổi, bổ sung một số điều của Luật Ban hành văn bản quy phạm pháp luật ngày 18 tháng 6 năm 2020;",
    categoryId: "administrative",
  },
  {
    docCode: "34/2016/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều và biện pháp thi hành Luật Ban hành văn bản quy phạm pháp luật",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2016-05-14",
    effectiveDate: "2016-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 34/2016/NĐ-CP ngày 14 tháng 5 năm 2016 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật Ban hành văn bản quy phạm pháp luật;",
    categoryId: "administrative",
  },
  {
    docCode: "154/2020/NĐ-CP",
    title: "Nghị định sửa đổi, bổ sung một số điều của Nghị định số 34/2016/NĐ-CP",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-12-31",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 154/2020/NĐ-CP ngày 31 tháng 12 năm 2020 của Chính phủ sửa đổi, bổ sung một số điều của Nghị định số 34/2016/NĐ-CP;",
    categoryId: "administrative",
  },
  {
    docCode: "77/2015/QH13",
    title: "Luật Tổ chức Chính phủ",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-06-19",
    effectiveDate: "2016-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Tổ chức Chính phủ ngày 19 tháng 6 năm 2015;",
    categoryId: "administrative",
  },
  {
    docCode: "47/2019/QH14",
    title: "Luật sửa đổi, bổ sung một số điều của Luật Tổ chức Chính phủ và Luật Tổ chức chính quyền địa phương",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2019-11-22",
    effectiveDate: "2020-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật sửa đổi, bổ sung một số điều của Luật Tổ chức Chính phủ và Luật Tổ chức chính quyền địa phương ngày 22 tháng 11 năm 2019;",
    categoryId: "administrative",
  },
  {
    docCode: "76/2015/QH13",
    title: "Luật Tổ chức chính quyền địa phương",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-06-19",
    effectiveDate: "2016-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Tổ chức chính quyền địa phương ngày 19 tháng 6 năm 2015;",
    categoryId: "administrative",
  },
  {
    docCode: "22/2008/QH12",
    title: "Luật Cán bộ, công chức",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2008-11-13",
    effectiveDate: "2010-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Cán bộ, công chức ngày 13 tháng 11 năm 2008;",
    categoryId: "administrative",
  },
  {
    docCode: "52/2019/QH14",
    title: "Luật sửa đổi, bổ sung một số điều của Luật Cán bộ, công chức và Luật Viên chức",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2019-11-25",
    effectiveDate: "2020-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật sửa đổi, bổ sung một số điều của Luật Cán bộ, công chức và Luật Viên chức ngày 25 tháng 11 năm 2019;",
    categoryId: "administrative",
  },
  {
    docCode: "58/2010/QH12",
    title: "Luật Viên chức",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2010-11-15",
    effectiveDate: "2012-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Viên chức ngày 15 tháng 11 năm 2010;",
    categoryId: "administrative",
  },
  {
    docCode: "138/2020/NĐ-CP",
    title: "Nghị định quy định về tuyển dụng, sử dụng và quản lý công chức",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-11-27",
    effectiveDate: "2020-12-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 138/2020/NĐ-CP ngày 27 tháng 11 năm 2020 của Chính phủ quy định về tuyển dụng, sử dụng và quản lý công chức;",
    categoryId: "administrative",
  },
  {
    docCode: "115/2020/NĐ-CP",
    title: "Nghị định quy định về tuyển dụng, sử dụng và quản lý viên chức",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-09-25",
    effectiveDate: "2020-09-29",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 115/2020/NĐ-CP ngày 25 tháng 9 năm 2020 của Chính phủ quy định về tuyển dụng, sử dụng và quản lý viên chức;",
    categoryId: "administrative",
  },
  {
    docCode: "112/2020/NĐ-CP",
    title: "Nghị định về xử lý kỷ luật cán bộ, công chức, viên chức",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-09-18",
    effectiveDate: "2020-09-20",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 112/2020/NĐ-CP ngày 18 tháng 9 năm 2020 của Chính phủ về xử lý kỷ luật cán bộ, công chức, viên chức;",
    categoryId: "administrative",
  },
  {
    docCode: "71/2023/NĐ-CP",
    title: "Nghị định sửa đổi, bổ sung một số điều của Nghị định số 112/2020/NĐ-CP",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2023-09-20",
    effectiveDate: "2023-09-20",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 71/2023/NĐ-CP ngày 20 tháng 9 năm 2023 của Chính phủ sửa đổi, bổ sung một số điều của Nghị định số 112/2020/NĐ-CP;",
    categoryId: "administrative",
  },
  {
    docCode: "90/2020/NĐ-CP",
    title: "Nghị định về đánh giá, xếp loại chất lượng cán bộ, công chức, viên chức",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-08-13",
    effectiveDate: "2020-08-20",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 90/2020/NĐ-CP ngày 13 tháng 8 năm 2020 của Chính phủ về đánh giá, xếp loại chất lượng cán bộ, công chức, viên chức;",
    categoryId: "administrative",
  },
  {
    docCode: "01/2011/QH13",
    title: "Luật Lưu trữ",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2011-11-11",
    effectiveDate: "2012-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Lưu trữ ngày 11 tháng 11 năm 2011;",
    categoryId: "administrative",
  },
  {
    docCode: "33/2024/QH15",
    title: "Luật Lưu trữ 2024",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2024-06-21",
    effectiveDate: "2025-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Lưu trữ ngày 21 tháng 6 năm 2024;",
    categoryId: "administrative",
  },

  // --- 2. DOANH NGHIỆP, THƯƠNG MẠI, ĐẦU TƯ ---
  {
    docCode: "59/2020/QH14",
    title: "Luật Doanh nghiệp",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2020-06-17",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Doanh nghiệp ngày 17 tháng 6 năm 2020;",
    categoryId: "enterprise",
  },
  {
    docCode: "01/2021/NĐ-CP",
    title: "Nghị định về đăng ký doanh nghiệp",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2021-01-04",
    effectiveDate: "2021-01-04",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 01/2021/NĐ-CP ngày 04 tháng 01 năm 2021 của Chính phủ về đăng ký doanh nghiệp;",
    categoryId: "enterprise",
  },
  {
    docCode: "61/2020/QH14",
    title: "Luật Đầu tư",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2020-06-17",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Đầu tư ngày 17 tháng 6 năm 2020;",
    categoryId: "enterprise",
  },
  {
    docCode: "31/2021/NĐ-CP",
    title: "Nghị định quy định chi tiết và hướng dẫn thi hành một số điều của Luật Đầu tư",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2021-03-26",
    effectiveDate: "2021-03-26",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 31/2021/NĐ-CP ngày 26 tháng 3 năm 2021 của Chính phủ quy định chi tiết và hướng dẫn thi hành một số điều của Luật Đầu tư;",
    categoryId: "enterprise",
  },
  {
    docCode: "36/2005/QH11",
    title: "Luật Thương mại",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2005-06-14",
    effectiveDate: "2006-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Thương mại ngày 14 tháng 6 năm 2005;",
    categoryId: "enterprise",
  },
  {
    docCode: "91/2015/QH13",
    title: "Bộ luật Dân sự",
    docType: "Bộ luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-11-24",
    effectiveDate: "2017-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Bộ luật Dân sự ngày 24 tháng 11 năm 2015;",
    categoryId: "enterprise",
  },
  {
    docCode: "54/2019/QH14",
    title: "Luật Chứng khoán",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2019-11-26",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Chứng khoán ngày 26 tháng 11 năm 2019;",
    categoryId: "enterprise",
  },
  {
    docCode: "155/2020/NĐ-CP",
    title: "Nghị định quy định chi tiết thi hành một số điều của Luật Chứng khoán",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-12-31",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 155/2020/NĐ-CP ngày 31 tháng 12 năm 2020 của Chính phủ quy định chi tiết thi hành một số điều của Luật Chứng khoán;",
    categoryId: "enterprise",
  },
  {
    docCode: "23/2018/QH14",
    title: "Luật Cạnh tranh",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2018-06-12",
    effectiveDate: "2019-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Cạnh tranh ngày 12 tháng 6 năm 2018;",
    categoryId: "enterprise",
  },
  {
    docCode: "35/2019/NĐ-CP",
    title: "Nghị định quy định chi tiết thi hành một số điều của Luật Cạnh tranh",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2019-03-24",
    effectiveDate: "2019-05-15",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 35/2019/NĐ-CP ngày 24 tháng 3 năm 2019 của Chính phủ quy định chi tiết thi hành một số điều của Luật Cạnh tranh;",
    categoryId: "enterprise",
  },

  // --- 3. LAO ĐỘNG & BẢO HIỂM XÃ HỘI ---
  {
    docCode: "45/2019/QH14",
    title: "Bộ luật Lao động",
    docType: "Bộ luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2019-11-20",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Bộ luật Lao động ngày 20 tháng 11 năm 2019;",
    categoryId: "hr",
  },
  {
    docCode: "145/2020/NĐ-CP",
    title: "Nghị định quy định chi tiết và hướng dẫn thi hành một số điều của Bộ luật Lao động về điều kiện lao động và quan hệ lao động",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-12-14",
    effectiveDate: "2021-02-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 145/2020/NĐ-CP ngày 14 tháng 12 năm 2020 của Chính phủ quy định chi tiết và hướng dẫn thi hành một số điều của Bộ luật Lao động về điều kiện lao động và quan hệ lao động;",
    categoryId: "hr",
  },
  {
    docCode: "12/2022/NĐ-CP",
    title: "Nghị định quy định về xử phạt vi phạm hành chính trong lĩnh vực lao động, bảo hiểm xã hội, người lao động Việt Nam đi làm việc ở nước ngoài theo hợp đồng",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2022-01-17",
    effectiveDate: "2022-01-17",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 12/2022/NĐ-CP ngày 17 tháng 01 năm 2022 của Chính phủ quy định về xử phạt vi phạm hành chính trong lĩnh vực lao động, bảo hiểm xã hội;",
    categoryId: "hr",
  },
  {
    docCode: "58/2014/QH13",
    title: "Luật Bảo hiểm xã hội",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2014-11-20",
    effectiveDate: "2016-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Bảo hiểm xã hội ngày 20 tháng 11 năm 2014;",
    categoryId: "hr",
  },
  {
    docCode: "41/2024/QH15",
    title: "Luật Bảo hiểm xã hội 2024",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2024-06-29",
    effectiveDate: "2025-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Bảo hiểm xã hội ngày 29 tháng 6 năm 2024;",
    categoryId: "hr",
  },
  {
    docCode: "115/2015/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều của Luật Bảo hiểm xã hội về bảo hiểm xã hội bắt buộc",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2015-11-11",
    effectiveDate: "2016-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 115/2015/NĐ-CP ngày 11 tháng 11 năm 2015 của Chính phủ quy định chi tiết một số điều của Luật Bảo hiểm xã hội về bảo hiểm xã hội bắt buộc;",
    categoryId: "hr",
  },
  {
    docCode: "84/2015/QH13",
    title: "Luật An toàn, vệ sinh lao động",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-06-25",
    effectiveDate: "2016-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật An toàn, vệ sinh lao động ngày 25 tháng 6 năm 2015;",
    categoryId: "hr",
  },
  {
    docCode: "39/2016/NĐ-CP",
    title: "Nghị định quy định chi tiết thi hành một số điều của Luật An toàn, vệ sinh lao động",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2016-05-15",
    effectiveDate: "2016-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 39/2016/NĐ-CP ngày 15 tháng 5 năm 2016 của Chính phủ quy định chi tiết thi hành một số điều của Luật An toàn, vệ sinh lao động;",
    categoryId: "hr",
  },
  {
    docCode: "38/2013/QH13",
    title: "Luật Việc làm",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2013-11-16",
    effectiveDate: "2015-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Việc làm ngày 16 tháng 11 năm 2013;",
    categoryId: "hr",
  },

  // --- 4. XÂY DỰNG, ĐẤU THẦU, ĐẦU TƯ CÔNG, QUY HOẠCH ---
  {
    docCode: "22/2023/QH15",
    title: "Luật Đấu thầu",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2023-06-23",
    effectiveDate: "2024-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Đấu thầu ngày 23 tháng 6 năm 2023;",
    categoryId: "construction",
  },
  {
    docCode: "24/2024/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều và biện pháp thi hành Luật Đấu thầu về lựa chọn nhà thầu",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2024-02-27",
    effectiveDate: "2024-02-27",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 24/2024/NĐ-CP ngày 27 tháng 02 năm 2024 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật Đấu thầu về lựa chọn nhà thầu;",
    categoryId: "construction",
  },
  {
    docCode: "50/2014/QH13",
    title: "Luật Xây dựng",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2014-06-18",
    effectiveDate: "2015-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Xây dựng ngày 18 tháng 6 năm 2014;",
    categoryId: "construction",
  },
  {
    docCode: "62/2020/QH14",
    title: "Luật sửa đổi, bổ sung một số điều của Luật Xây dựng",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2020-06-17",
    effectiveDate: "2021-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật sửa đổi, bổ sung một số điều của Luật Xây dựng ngày 17 tháng 6 năm 2020;",
    categoryId: "construction",
  },
  {
    docCode: "10/2021/NĐ-CP",
    title: "Nghị định về quản lý chi phí đầu tư xây dựng",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2021-02-09",
    effectiveDate: "2021-02-09",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 10/2021/NĐ-CP ngày 09 tháng 02 năm 2021 của Chính phủ về quản lý chi phí đầu tư xây dựng;",
    categoryId: "construction",
  },
  {
    docCode: "15/2021/NĐ-CP",
    title: "Nghị định quy định chi tiết một số nội dung về quản lý dự án đầu tư xây dựng",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2021-03-03",
    effectiveDate: "2021-03-03",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 15/2021/NĐ-CP ngày 03 tháng 3 năm 2021 của Chính phủ quy định chi tiết một số nội dung về quản lý dự án đầu tư xây dựng;",
    categoryId: "construction",
  },
  {
    docCode: "06/2021/NĐ-CP",
    title: "Nghị định quy định chi tiết về quản lý chất lượng, thi công xây dựng và bảo trì công trình xây dựng",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2021-01-26",
    effectiveDate: "2021-01-26",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 06/2021/NĐ-CP ngày 26 tháng 01 năm 2021 của Chính phủ quy định chi tiết về quản lý chất lượng, thi công xây dựng và bảo trì công trình xây dựng;",
    categoryId: "construction",
  },
  {
    docCode: "39/2019/QH14",
    title: "Luật Đầu tư công",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2019-06-13",
    effectiveDate: "2020-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Đầu tư công ngày 13 tháng 6 năm 2019;",
    categoryId: "construction",
  },
  {
    docCode: "40/2020/NĐ-CP",
    title: "Nghị định quy định chi tiết thi hành một số điều của Luật Đầu tư công",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-04-06",
    effectiveDate: "2020-04-06",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 40/2020/NĐ-CP ngày 06 tháng 4 năm 2020 của Chính phủ quy định chi tiết thi hành một số điều của Luật Đầu tư công;",
    categoryId: "construction",
  },
  {
    docCode: "21/2017/QH14",
    title: "Luật Quy hoạch",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2017-11-24",
    effectiveDate: "2019-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Quy hoạch ngày 24 tháng 11 năm 2017;",
    categoryId: "construction",
  },

  // --- 5. ĐẤT ĐAI, NHÀ Ở, BẤT ĐỘNG SẢN ---
  {
    docCode: "31/2024/QH15",
    title: "Luật Đất đai 2024",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2024-01-18",
    effectiveDate: "2024-08-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Đất đai ngày 18 tháng 01 năm 2024;",
    categoryId: "property",
  },
  {
    docCode: "102/2024/NĐ-CP",
    title: "Nghị định quy định chi tiết thi hành một số điều của Luật Đất đai",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2024-07-30",
    effectiveDate: "2024-08-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 102/2024/NĐ-CP ngày 30 tháng 7 năm 2024 của Chính phủ quy định chi tiết thi hành một số điều của Luật Đất đai;",
    categoryId: "property",
  },
  {
    docCode: "71/2024/NĐ-CP",
    title: "Nghị định quy định về giá đất",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2024-06-27",
    effectiveDate: "2024-08-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 71/2024/NĐ-CP ngày 27 tháng 6 năm 2024 của Chính phủ quy định về giá đất;",
    categoryId: "property",
  },
  {
    docCode: "27/2023/QH15",
    title: "Luật Nhà ở",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2023-11-27",
    effectiveDate: "2024-08-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Nhà ở ngày 27 tháng 11 năm 2023;",
    categoryId: "property",
  },
  {
    docCode: "95/2024/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều của Luật Nhà ở",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2024-07-24",
    effectiveDate: "2024-08-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 95/2024/NĐ-CP ngày 24 tháng 7 năm 2024 của Chính phủ quy định chi tiết một số điều của Luật Nhà ở;",
    categoryId: "property",
  },
  {
    docCode: "29/2023/QH15",
    title: "Luật Kinh doanh bất động sản",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2023-11-28",
    effectiveDate: "2024-08-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Kinh doanh bất động sản ngày 28 tháng 11 năm 2023;",
    categoryId: "property",
  },
  {
    docCode: "96/2024/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều của Luật Kinh doanh bất động sản",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2024-07-24",
    effectiveDate: "2024-08-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 96/2024/NĐ-CP ngày 24 tháng 7 năm 2024 của Chính phủ quy định chi tiết một số điều của Luật Kinh doanh bất động sản;",
    categoryId: "property",
  },

  // --- 6. TÀI CHÍNH, KẾ TOÁN, NGÂN SÁCH, THUẾ ---
  {
    docCode: "83/2015/QH13",
    title: "Luật Ngân sách nhà nước",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-06-25",
    effectiveDate: "2017-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Ngân sách nhà nước ngày 25 tháng 6 năm 2015;",
    categoryId: "enterprise",
  },
  {
    docCode: "163/2016/NĐ-CP",
    title: "Nghị định quy định chi tiết thi hành một số điều của Luật Ngân sách nhà nước",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2016-12-21",
    effectiveDate: "2017-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 163/2016/NĐ-CP ngày 21 tháng 12 năm 2016 của Chính phủ quy định chi tiết thi hành một số điều của Luật Ngân sách nhà nước;",
    categoryId: "enterprise",
  },
  {
    docCode: "88/2015/QH13",
    title: "Luật Kế toán",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-11-20",
    effectiveDate: "2017-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Kế toán ngày 20 tháng 11 năm 2015;",
    categoryId: "enterprise",
  },
  {
    docCode: "174/2016/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều của Luật Kế toán",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2016-12-30",
    effectiveDate: "2017-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 174/2016/NĐ-CP ngày 30 tháng 12 năm 2016 của Chính phủ quy định chi tiết một số điều của Luật Kế toán;",
    categoryId: "enterprise",
  },
  {
    docCode: "38/2019/QH14",
    title: "Luật Quản lý thuế",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2019-06-13",
    effectiveDate: "2020-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Quản lý thuế ngày 13 tháng 6 năm 2019;",
    categoryId: "enterprise",
  },
  {
    docCode: "126/2020/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều của Luật Quản lý thuế",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-10-19",
    effectiveDate: "2020-12-05",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 126/2020/NĐ-CP ngày 19 tháng 10 năm 2020 của Chính phủ quy định chi tiết một số điều của Luật Quản lý thuế;",
    categoryId: "enterprise",
  },
  {
    docCode: "123/2020/NĐ-CP",
    title: "Nghị định quy định về hóa đơn, chứng từ",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2020-10-19",
    effectiveDate: "2022-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 123/2020/NĐ-CP ngày 19 tháng 10 năm 2020 của Chính phủ quy định về hóa đơn, chứng từ;",
    categoryId: "enterprise",
  },
  {
    docCode: "78/2021/TT-BTC",
    title: "Thông tư hướng dẫn thực hiện một số điều của Luật Quản lý thuế và Nghị định số 123/2020/NĐ-CP về hóa đơn, chứng từ",
    docType: "Thông tư",
    issuingAuthority: "Bộ Tài chính",
    issuedDate: "2021-09-17",
    effectiveDate: "2022-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Thông tư số 78/2021/TT-BTC ngày 17 tháng 9 năm 2021 của Bộ trưởng Bộ Tài chính hướng dẫn về hóa đơn, chứng từ;",
    categoryId: "enterprise",
  },

  // --- 7. CÔNG NGHỆ, AN NINH MẠNG, BẢO VỆ DỮ LIỆU CÁ NHÂN ---
  {
    docCode: "20/2023/QH15",
    title: "Luật Giao dịch điện tử",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2023-06-22",
    effectiveDate: "2024-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Giao dịch điện tử ngày 22 tháng 6 năm 2023;",
    categoryId: "enterprise",
  },
  {
    docCode: "86/2015/QH13",
    title: "Luật An toàn thông tin mạng",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2015-11-19",
    effectiveDate: "2016-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật An toàn thông tin mạng ngày 19 tháng 11 năm 2015;",
    categoryId: "enterprise",
  },
  {
    docCode: "24/2018/QH14",
    title: "Luật An ninh mạng",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2018-06-12",
    effectiveDate: "2019-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật An ninh mạng ngày 12 tháng 6 năm 2018;",
    categoryId: "enterprise",
  },
  {
    docCode: "13/2023/NĐ-CP",
    title: "Nghị định về bảo vệ dữ liệu cá nhân",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2023-04-17",
    effectiveDate: "2023-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 13/2023/NĐ-CP ngày 17 tháng 4 năm 2023 của Chính phủ về bảo vệ dữ liệu cá nhân;",
    categoryId: "enterprise",
  },
  {
    docCode: "73/2019/NĐ-CP",
    title: "Nghị định quy định quản lý đầu tư ứng dụng công nghệ thông tin sử dụng nguồn vốn ngân sách nhà nước",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2019-09-05",
    effectiveDate: "2020-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 73/2019/NĐ-CP ngày 05 tháng 9 năm 2019 của Chính phủ quy định quản lý đầu tư ứng dụng công nghệ thông tin sử dụng nguồn vốn ngân sách nhà nước;",
    categoryId: "construction",
  },

  // --- 8. GIÁO DỤC, Y TẾ, THANH TRA, KHIẾU NẠI ---
  {
    docCode: "43/2019/QH14",
    title: "Luật Giáo dục",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2019-06-14",
    effectiveDate: "2020-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Giáo dục ngày 14 tháng 6 năm 2019;",
    categoryId: "administrative",
  },
  {
    docCode: "34/2018/QH14",
    title: "Luật sửa đổi, bổ sung một số điều của Luật Giáo dục đại học",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2018-11-19",
    effectiveDate: "2019-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật sửa đổi, bổ sung một số điều của Luật Giáo dục đại học ngày 19 tháng 11 năm 2018;",
    categoryId: "administrative",
  },
  {
    docCode: "15/2023/QH15",
    title: "Luật Khám bệnh, chữa bệnh",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2023-01-09",
    effectiveDate: "2024-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Khám bệnh, chữa bệnh ngày 09 tháng 01 năm 2023;",
    categoryId: "administrative",
  },
  {
    docCode: "11/2022/QH15",
    title: "Luật Thanh tra",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2022-11-14",
    effectiveDate: "2023-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Thanh tra ngày 14 tháng 11 năm 2022;",
    categoryId: "administrative",
  },
  {
    docCode: "43/2023/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều và biện pháp thi hành Luật Thanh tra",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2023-06-30",
    effectiveDate: "2023-08-15",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 43/2023/NĐ-CP ngày 30 tháng 6 năm 2023 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật Thanh tra;",
    categoryId: "administrative",
  },
  {
    docCode: "02/2011/QH13",
    title: "Luật Khiếu nại",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2011-11-11",
    effectiveDate: "2012-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Khiếu nại ngày 11 tháng 11 năm 2011;",
    categoryId: "administrative",
  },
  {
    docCode: "25/2018/QH14",
    title: "Luật Tố cáo",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2018-06-12",
    effectiveDate: "2019-01-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Tố cáo ngày 12 tháng 6 năm 2018;",
    categoryId: "administrative",
  },
  {
    docCode: "36/2018/QH14",
    title: "Luật Phòng, chống tham nhũng",
    docType: "Luật",
    issuingAuthority: "Quốc hội",
    issuedDate: "2018-11-20",
    effectiveDate: "2019-07-01",
    status: "ACTIVE",
    fullCitation: "Căn cứ Luật Phòng, chống tham nhũng ngày 20 tháng 11 năm 2018;",
    categoryId: "administrative",
  },
  {
    docCode: "59/2019/NĐ-CP",
    title: "Nghị định quy định chi tiết một số điều và biện pháp thi hành Luật Phòng, chống tham nhũng",
    docType: "Nghị định",
    issuingAuthority: "Chính phủ",
    issuedDate: "2019-07-01",
    effectiveDate: "2019-08-15",
    status: "ACTIVE",
    fullCitation: "Căn cứ Nghị định số 59/2019/NĐ-CP ngày 01 tháng 7 năm 2019 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật Phòng, chống tham nhũng;",
    categoryId: "administrative",
  },
];
